name: Checks Workflow

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  checks:
    name: Checks Workflow
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov mypy
          pip install -r requirements.txt

      - name: Unit Tests
        run: |
          pytest tests

      - name: Static tests
        run: |
          mypy SpaceBattle

      - name: Generate coverage report
        run: |
          pytest --cache-clear --cov=. --cov-report=xml tests > pytest-coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: pytest-coverage.xml
          flags: unittests
          fail_ci_if_error: true
